name: Orange CI Pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-assets:
    uses: tastyigniter/workflows/.github/workflows/build-assets.yml@main
    with:
      commit-file-pattern: assets/
  php-lint:
    needs: build-assets
    if: ${{ always() && needs.build-assets.result == 'success' }}
    uses: tastyigniter/workflows/.github/workflows/php-lint.yml@main
    with:
      composer: update --no-interaction --no-progress
  php-tests:
    needs: php-lint
    if: ${{ always() && needs.php-lint.result == 'success' }}
    strategy:
      matrix:
        php: [ '8.2', '8.3' ]
    uses: tastyigniter/workflows/.github/workflows/php-tests.yml@main
    with:
      php-version: ${{ matrix.target }}
      composer: update --no-interaction --no-progress
