name: Orange CI Pipeline

on: [ push, workflow_dispatch ]

jobs:
  build-assets:
    permissions:
      contents: write
    uses: tastyigniter/workflows/.github/workflows/build-assets.yml@main
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  php-tests:
    needs: build-assets
    if: ${{ always() && needs.build-assets.result == 'success' }}
    strategy:
      matrix:
        php: [ '8.3', '8.4' ]
    uses: tastyigniter/workflows/.github/workflows/php-tests.yml@main
    with:
      php-version: ${{ matrix.target }}
      composer: update --no-interaction --no-progress
